### ISSUE TITLE
Wrong installation command

### ISSUE THREAD

**Issue by icebob** [r2d2bzh/moleculer-cron#2]
Hi,

Some users pointed out that the npm installation command is wrong and install a different (originally forked) library.

```
$ npm install moleculer-cron --save
```

The correct one should be 
```
$ npm install @r2d2bzh/moleculer-cron --save
```

**Comment by furanzujin** [comment]
Hi there,

The documentation has been fixed in the [latest release](https://www.npmjs.com/package/@r2d2bzh/moleculer-cron).
